### ISSUE TITLE
a query question

### ISSUE THREAD

**Issue by gyf329** [flowable/flowable-mongodb#6]
When i want query someone’s uncompleted usertasks,but it seems return all tasks (include other people).How can i do?or modify your code self?plz give me some suggests,thank you very much!
![image](https://github.com/flowable/flowable-mongodb/assets/78125223/49454e85-9209-4279-b3ee-47ef50bdb334)

**Comment by tijsrademakers** [comment]
You can indeed modify the code yourself and contribute it back to the project if that's possible for you.
